### PR TITLE
fix top-right icons order

### PR DESCRIPTION
**Pull request by noamoss**
elegant soultion to icons order issue

### CODE REVIEW

**Comment by florpor** [comment]
Looks better since notifier and forum links are always there and fb and twitter aren't, but still if there isn't a fb page but there is a twitter one it will still look weird (twitter one will be one empty space away from the forum link)..
Can you maybe also change the way these icons are hidden and shown to use the "display" css property so that when they are hidden (display: none) they will not take any space?

**Comment by noamoss** [comment]
@niryariv ??

**Comment by niryariv** [comment]
@noamoss what's the status? did u fix per @florpor's comment?

**Comment by noamoss** [comment]
@niryariv yep. Please check it is what you want.

**Comment by niryariv** [comment]
unless I'm missing something it's the same ?

screen shot 2016-07-24 at 1 01 54 pm

**Comment by noamoss** [comment]
@niryariv fixed on:
https://github.com/niryariv/opentaba-client/commit/3a2b06c4467f00035d80340473ec5699ee01bd0b

**Pull request closed without merging**
