### PR TITLE
email notifier service (beta)

### PR DESCRIPTION
**Pull request by noamoss**

### CODE REVIEW

**Comment by alonisser** [comment]
Ok looks good, But please explain more:
1. What is notifier service, yours? public ? something else?
2. Does the user needs to authenticate in some way? does the system "remember" his email or does he have to enter it everytime?

**Comment by noamoss** [comment]
@alonisser 
1. It is something we build to enable (regular) users to recieve costumized updates from Eknights. (read more at [here](http://wiki.hasadna.org.il/wiki/%D7%94%D7%A6%D7%99%D7%A4%D7%95%D7%A8_%D7%94%D7%A7%D7%98%D7%A0%D7%94)
2. For now user needs to supply email+password. I hope to change to no password login soon. Found [this](https://pypi.python.org/pypi/flask-passwordless/0.1.0), but not sure yet about the implementation.

**Comment by niryariv** [comment]
@noamoss 

* I tested locally, getting an error from the server. It might be due to inaccessible URL in the parameters: 
``http://82.196.4.213/addfeed/opentaba?city=%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D&link=http://0.0.0.0:5000//plans.atom``

(also note extra / before /plans.atom)

* The URL should be real domain name, not IP address - it makes it look like some phishing site.

**Comment by noamoss** [comment]
fixed (see below). I will repush the fix once the notifier server will be up again.

**Comment by niryariv** [comment]
looks good, I like the new icon

**Comment by alonisser** [comment]
+1 for the new icon

**Pull request closed without merging**
